apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sydent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sydent.name" . }}
    helm.sh/chart: {{ include "sydent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sydent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sydent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: config
        secret:
          {{- if .Values.existingConfigSecret }}
          secretName: {{ .Values.existingConfigSecret }}
          {{- else }}
          secretName: {{ template "sydent.fullname" . }}-config
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.digest | default "" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /home/sydent/sydent.conf
            subPath: sydent.conf
            readOnly: true
          {{- if .Values.persistence.enabled }}
          - name: database
            mountPath: /home/sydent/sydent.db
            subPath: sydent.db
          {{- end }}
          livenessProbe:
            httpGet:
                path: /_matrix/identity/api/v1/pubkey/ed25519:0
              port: http
          readinessProbe:
            httpGet:
              path: /_matrix/identity/api/v1/pubkey/ed25519:0
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
