apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sydent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sydent.name" . }}
    helm.sh/chart: {{ include "sydent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sydent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sydent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes: {{ if and (not .Values.config) (not .Values.persistence.enabled) }}[]{{ end }}
      {{- if .Values.config }}
      - name: config
        configMap:
          name: {{ include "sydent.fullname" . }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      - name: database
        persistentVolumeClaim:
          claimName: {{ include "sydent.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.digest | default "" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          volumeMounts: {{ if and (not .Values.config) (not .Values.persistence.enabled) }}[]{{ end }}
          {{- if .Values.config }}
          - name: config
            mountPath: /home/sydent/sydent.conf
            subPath: sydent.conf
            readOnly: false
          {{- end }}
          {{- if .Values.persistence.enabled }}
          - name: database
            mountPath: /home/sydent/database
          {{- end }}
          livenessProbe:
            httpGet:
              path: "/_matrix/identity/api/v1/pubkey/ed25519:0"
              port: http
          readinessProbe:
            httpGet:
              path: "/_matrix/identity/api/v1/pubkey/ed25519:0"
              port: http
          securityContext:
            fsGroup: 1000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
