{{- if or (not .Values.existingConfigSecret) or .Values.sydent_config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sydent.fullname" . }}-config
  labels:
    app: {{ template "sydent.name" . }}
    chart: {{ template "sydent.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sydent.conf: |
		[http]
		replication.https.bind_address = ::
		internalapi.http.port =
		replication.https.port = 4434
		replication.https.certfile =
		obey_x_forwarded_for = False
		clientapi.http.bind_address = ::
		clientapi.http.port = 8090
		federation.verifycerts = True
		replication.https.cacert =

		[db]
		db.file = sydent.db

		[sms]
		bodytemplate = Your code is {token}

		[crypto]
		ed25519.signingkey = ed25519 0 M1I8gPYIvFT9rhdV/6l2W0jm1CJQ07bcikqFbmlci0g

		[general]
		log.path =
		log.level = INFO
		pidfile.path = sydent.pid
		server.name = rude-salamander-sydent-5c8d9bcdbf-4mw6v

		[email]
		email.smtpusername =
		email.smtppassword =
		email.smtphost = localhost
		email.hostname =
		email.smtpport = 25
		email.tlsmode = 0
		email.template = /home/sydent/emails/
		email.from = Sydent Validation <noreply@{hostname}>
		email.invite.subject = %(sender_display_name)s has invited you to chat
		email.subject = Your Validation Token
	{{- end }}
