{{- if or (not .Values.existingSecret) .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mtls.fullname" . }}-certs
  labels:
    app: {{ template "mtls.name" . }}
    chart: {{ template "mtls.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.secrets.interemediateDomain }}
  ca.crt: |-
{{ .Files.Get "output/ca/intermediate/{{ .Values.secrets.interemediateDomain }}/certs/{{ .Values.secrets.interemediateDomain}}.cert.pem" | b64enc | indent 4 }}
{{- else }}
  ca.crt: |-
{{ .Files.Get "output/ca/certs/ca.cert.pem" | b64enc | indent 4 }}
{{- end }}
{{- end -}}
